#!/bin/bash
#SBATCH --time=04:30:00   # walltime
#SBATCH --ntasks=1   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem-per-cpu=1024M   # memory per CPU core
#SBATCH -J "accelrad"   # job name
#SBATCH --gid=fslg_dronesim
module unload matlab
module load matlab/r2015b
matlab -r "slave(${1},${2},${3})"
sleep .1
matlab -r "slave(${1},${2},${3})"
sleep .1
matlab -r "slave(${1},${2},${3})"
sleep .1
matlab -r "slave(${1},${2},${3})"

