#!/bin/bash

dronenums1=100
droneaccel2=0
droneinfringement3=0
for repeats in {1..5}
do
for dronechanger1 in {0..5}
do
for dronechanger2 in {1..10}
do
echo ${repeat}
echo ${dronechanger1}*.1
echo ${dronechanger2}*.0001
sbatch droneapocalypse30trials  ${dronenums1} ${dronechanger2}*.0001 ${dronechanger1}*.2+1
done
done
done
